name: openapi-generate-cli

on:
  push:
    branches:
      - main
    paths: 
      - '**/petstore.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: myoshi1012/openapi-client-repo
          path: client

      - name: Generate OpenAPI client
        uses: docker://openapitools/openapi-generator-cli
        with:
          args: >-
            generate 
            -i ./petstore.yaml 
            -g typescript-axios 
            -o ./client/autogen

      - name: Grant file permissions
        run: |
          sudo chown -R $USER:$USER .

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: client
          commit-message: update client
          title: update client
          body: update client
          branch: feature/update_client
          branch-suffix: short-commit-hash # 同じプルリクは作らない
